### ISSUE TITLE
[Unconfirmed] Crash on right clicking user in VC

### ISSUE THREAD

**Issue by UsboKirishima** [GooseMod/GooseMod#65] opened 2022-02-23 20:21 UTC
**Describe the bug**
When you right click on user in a voice chat discord crashes. 
**To Reproduce**
1. Go to 'a server'
2. Right Click on 'a user in a voice chat'

(You should be able to find the following information in the bottom of your settings.)

**GooseMod info:**
 - Modules: (Custom CSS)

**Discord info:**
 - Update Channel: (Stable)
 - OS: (Linux)

**Comment by CanadaHonk** [comment] 2022-02-23 20:23
Can't reproduce. Can you copy your debug info via the button in GM settings?

**Comment by CanadaHonk** [comment] 2022-02-24 20:08
Closing due to lack of details and repro, comment with additional information if the issue remains.

**Closed by CanadaHonk** 2022-02-24 20:08 UTC
Labels: type: bug
